### ISSUE TITLE
some questions about batch size

### ISSUE THREAD

**Issue by krishnakanthnakka** [MasterBin-IIAU/CSA#1]
Hello,

If I increase batchsize in  https://github.com/MasterBin-IIAU/CSA/blob/efd69a5705dd21c6701fd4ae7922f3a44647069a/train1.py#L39, the data loader seems to have an issue. 

I presume it is because the shape of full search tensor will be different for different videos and the stacking it is a problem for batch size >1. Is there any way to increase batch size with the current code for improving training speed.

The other question, can you please tell the effect of batchsize param in baseoptions1.py in the training process, I don't see its effect anywhere expect few lines in train1.py which mostly has to do with updating total iters.

**Comment by MasterBin-IIAU** [comment]
@krishnakanthnakka 
Hi, thanks for your interest in our work! :) 
**The first question**. 
Your understanding is right. To train the perturbation generator, we hope to cool down the response maps and shrink the regression maps respectively. In code implementation, we use GOT10K_dataset to provide template and search regions.
https://github.com/MasterBin-IIAU/CSA/blob/master/train1.py#L38
The reason why we choose max_num=15 is that the memory size of 2080Ti is 11GB. If you have GPU with a larger memory size, you can change max_num to allow using more samples. You can also change the sampling interval to generate more data when we prepare the dataset. https://github.com/MasterBin-IIAU/CSA/blob/master/Unified_GOT10K_process.py.py#L9
In this way, you can roughly regard max_num as "batch size". :)

**The second question**.
The batchsize param in baseoption1.py doesn't have an effect on our training. This param is inherited from the original pix2pix codebase.

**Comment by krishnakanthnakka** [comment]
Thank you for your clarification.

Following up, can you please advise on the number of epochs you used for training standalone 1. search attack generator and   2. template attack generator.

I see from trainoptions1.py, it uses niter =100 epochs with constant lr and another niter_decay = 100 epochs with decaying lr. However, https://github.com/MasterBin-IIAU/CSA/blob/efd69a5705dd21c6701fd4ae7922f3a44647069a/train1.py#L46 uses 1 epoch and also released model uses the name 1_net_G.pth for search attack. 

Can you please advise on epochs you used for released search and template attack generators.

**Comment by MasterBin-IIAU** [comment]
@krishnakanthnakka 
Hi, we actually only train our generator for **1 epoch**. Experimental results show that the model has achieved good enough performance after 1 epoch's training. I guess this is also an advantage of our method. I mean the training time is quite short. 
In addition, you can feel free to overlook most of the arguments in trainoptions, because most of them are not used.

**Comment by krishnakanthnakka** [comment]
Wonderful. That's a really short training time I have come across in recent times.
