### ISSUE TITLE
I can't find the checkpoints folder.

### ISSUE THREAD

**Issue by shikaichao-hub** [MasterBin-IIAU/CSA#3]
The readme file says that we should download checkpoints you need, then put them under checkpoints/<MODEL_NAME>/. But I can't find the checkpoints folder. How to solve this problem？

**Comment by MasterBin-IIAU** [comment]
Hi, please create a directory called "checkpoints" then put the downloaded checkpoints under this folder.
This line of code may help you to better understand it.
https://github.com/MasterBin-IIAU/CSA/blob/efd69a5705dd21c6701fd4ae7922f3a44647069a/GAN_utils_search_0.py#L16
